const {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} = require('docx');
const { bandForPercent, MAX_RATING } = require('./performanceMeta');

const formatIsoDate = (value) => {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toISOString().slice(0, 10);
};

const formatDateTime = (value = new Date()) => {
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleString('en-NG', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

const safeFilenamePart = (value) =>
  String(value || 'staff')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'staff';

const text = (value) => {
  if (value == null || value === '') return '—';
  return String(value);
};

const thinBorder = {
  style: BorderStyle.SINGLE,
  size: 4,
  color: 'D1D5DB',
};

const cellBorders = {
  top: thinBorder,
  bottom: thinBorder,
  left: thinBorder,
  right: thinBorder,
};

const cell = (content, opts = {}) => {
  const {
    bold = false,
    width = 1200,
    fill = null,
    align = AlignmentType.LEFT,
  } = opts;
  return new TableCell({
    borders: cellBorders,
    width: { size: width, type: WidthType.DXA },
    shading: fill ? { fill } : undefined,
    children: [
      new Paragraph({
        alignment: align,
        children: [
          new TextRun({
            text: text(content),
            bold,
            size: 18,
            font: 'Calibri',
          }),
        ],
      }),
    ],
  });
};

const heading = (label, level = HeadingLevel.HEADING_1) =>
  new Paragraph({
    heading: level,
    spacing: { before: level === HeadingLevel.HEADING_1 ? 0 : 280, after: 120 },
    children: [
      new TextRun({
        text: label,
        bold: true,
        size: level === HeadingLevel.HEADING_1 ? 32 : 24,
        font: 'Calibri',
        color: '111827',
      }),
    ],
  });

const bodyPara = (label, value) =>
  new Paragraph({
    spacing: { after: 60 },
    children: [
      new TextRun({
        text: label ? `${label}: ` : '',
        bold: !!label,
        size: 20,
        font: 'Calibri',
        color: '374151',
      }),
      new TextRun({
        text: text(value),
        size: 20,
        font: 'Calibri',
        color: '1F2937',
      }),
    ],
  });

const mutedPara = (value) =>
  new Paragraph({
    spacing: { after: 80 },
    children: [
      new TextRun({
        text: text(value),
        italics: true,
        size: 18,
        font: 'Calibri',
        color: '6B7280',
      }),
    ],
  });

const bandLabel = (band) => {
  if (!band) return '—';
  return band.label || band.id || '—';
};

const filterLines = (filters = {}) => {
  const items = [];
  if (filters.search) items.push(`Search: ${filters.search}`);
  if (filters.department && filters.department !== 'all') {
    items.push(`Department: ${filters.department}`);
  }
  if (filters.companyName) {
    items.push(`Company: ${filters.companyName}`);
  } else if (filters.company && filters.company !== 'all') {
    items.push(`Company ID: ${filters.company}`);
  }
  if (filters.from) items.push(`From: ${filters.from}`);
  if (filters.to) items.push(`To: ${filters.to}`);
  return items;
};

const metaChildren = (generatedBy, filters) => {
  const byLine = generatedBy
    ? `${generatedBy.name || 'User'}${
        generatedBy.role ? ` (${generatedBy.role})` : ''
      }`
    : 'Unknown';
  const filterItems = filterLines(filters);
  const children = [
    bodyPara('Generated', formatDateTime(new Date())),
    bodyPara('Generated by', byLine),
    bodyPara(
      'Filters',
      filterItems.length ? filterItems.join('; ') : 'All staff (no filters applied)'
    ),
    new Paragraph({ spacing: { after: 160 }, children: [] }),
  ];
  return children;
};

const headerRow = (labels, widths) =>
  new TableRow({
    tableHeader: true,
    children: labels.map((label, i) =>
      cell(label, { bold: true, width: widths[i], fill: 'F3F4F6' })
    ),
  });

const questionsTable = (questions = []) => {
  if (!questions.length) {
    return [mutedPara('No questions recorded.')];
  }
  const widths = [2800, 2800, 2000, 900];
  return [
    new Table({
      width: { size: 8500, type: WidthType.DXA },
      columnWidths: widths,
      rows: [
        headerRow(['Question', 'Answer notes', 'Metric', 'Rating'], widths),
        ...questions.map(
          (q) =>
            new TableRow({
              children: [
                cell(q.prompt || '—', { width: widths[0] }),
                cell(q.answer || '—', { width: widths[1] }),
                cell(q.metric || '—', { width: widths[2] }),
                cell(`${q.rating ?? '—'}/${MAX_RATING}`, {
                  width: widths[3],
                  align: AlignmentType.CENTER,
                }),
              ],
            })
        ),
      ],
    }),
    new Paragraph({ spacing: { after: 120 }, children: [] }),
  ];
};

const assessmentChildren = (assessment) => {
  const aBand =
    assessment.status === 'completed'
      ? bandForPercent(assessment.scorePercent)
      : null;
  const conductor = assessment.conductedBy?.name
    ? ` · by ${assessment.conductedBy.name}`
    : '';
  const scoreLine = `${formatIsoDate(assessment.meetingDate)} · ${
    assessment.status || '—'
  } · ${assessment.totalScore ?? '—'}/${assessment.maxPossibleScore ?? '—'} (${
    assessment.scorePercent ?? '—'
  }%)${aBand ? ` · ${aBand.label}` : ''}${conductor}`;

  const children = [
    new Paragraph({
      spacing: { before: 120, after: 60 },
      children: [
        new TextRun({
          text: scoreLine,
          bold: true,
          size: 20,
          font: 'Calibri',
        }),
      ],
    }),
  ];
  if (assessment.overallNotes) {
    children.push(mutedPara(`Notes: ${assessment.overallNotes}`));
  }
  children.push(...questionsTable(assessment.questions || []));
  return children;
};

const staffDetailChildren = (card, assessments = []) => {
  const s = card.staff || {};
  const band =
    card.band ||
    (card.averagePercent != null ? bandForPercent(card.averagePercent) : null);
  const profile = [
    s.jobTitle ? `${s.jobTitle} · ` : '',
    s.department || 'No department',
    s.company?.name ? ` · ${s.company.name}` : '',
    s.status === 'inactive' ? ' · Inactive' : '',
  ].join('');

  const children = [
    heading(s.name || 'Staff', HeadingLevel.HEADING_2),
    mutedPara(profile || '—'),
    bodyPara(
      'Summary',
      `Assessments: ${card.assessmentCount ?? 0} · Average: ${
        card.averagePercent != null ? `${card.averagePercent}%` : '—'
      } · Band: ${bandLabel(band)} · Last assessed: ${formatIsoDate(
        card.latestAssessmentDate
      )}`
    ),
    heading('Assessment history', HeadingLevel.HEADING_3),
  ];

  if (!assessments.length) {
    children.push(
      mutedPara('No assessments recorded for this staff member.')
    );
  } else {
    for (const a of assessments) {
      children.push(...assessmentChildren(a));
    }
  }
  return children;
};

const rankingTable = (scorecards = []) => {
  const widths = [600, 1600, 1200, 1200, 1200, 900, 800, 1000, 1000];
  if (!scorecards.length) {
    return [mutedPara('No staff in the current filter set.')];
  }
  return [
    new Table({
      width: { size: 8500, type: WidthType.DXA },
      columnWidths: widths,
      rows: [
        headerRow(
          [
            'Rank',
            'Name',
            'Job title',
            'Department',
            'Company',
            '# Assess.',
            'Avg %',
            'Band',
            'Last assessed',
          ],
          widths
        ),
        ...scorecards.map((card) => {
          const s = card.staff || {};
          const band =
            card.band ||
            (card.averagePercent != null
              ? bandForPercent(card.averagePercent)
              : null);
          return new TableRow({
            children: [
              cell(card.rank != null ? card.rank : '—', { width: widths[0] }),
              cell(s.name || '—', { width: widths[1] }),
              cell(s.jobTitle || '—', { width: widths[2] }),
              cell(s.department || '—', { width: widths[3] }),
              cell(s.company?.name || '—', { width: widths[4] }),
              cell(card.assessmentCount ?? 0, {
                width: widths[5],
                align: AlignmentType.CENTER,
              }),
              cell(
                card.averagePercent != null ? `${card.averagePercent}%` : '—',
                { width: widths[6], align: AlignmentType.CENTER }
              ),
              cell(bandLabel(band), { width: widths[7] }),
              cell(formatIsoDate(card.latestAssessmentDate), {
                width: widths[8],
              }),
            ],
          });
        }),
      ],
    }),
  ];
};

const footerChildren = () => [
  new Paragraph({ spacing: { before: 360 }, children: [] }),
  mutedPara(
    `GAT Staff Performance Scorecards · rating scale 1–${MAX_RATING} per question · Bands: Needs attention < 50% · Solid 50–74% · Strong 75%+`
  ),
];

const packDocument = async (title, children) => {
  const doc = new Document({
    creator: 'GAT',
    title,
    description: 'GAT Staff Performance Scorecards',
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 720,
              right: 720,
              bottom: 720,
              left: 720,
            },
          },
        },
        children,
      },
    ],
  });
  return Packer.toBuffer(doc);
};

/**
 * Portfolio report: ranking table + per-staff detail with assessment Q/A.
 */
const buildPortfolioReportDocx = async ({
  scorecards = [],
  detailsByStaffId = {},
  generatedBy,
  filters,
} = {}) => {
  const getDetails = (id) => {
    if (detailsByStaffId instanceof Map) return detailsByStaffId.get(String(id));
    return detailsByStaffId[String(id)] || detailsByStaffId[id];
  };

  const children = [
    heading('GAT Staff Performance Scorecards'),
    ...metaChildren(generatedBy, filters),
    heading('Portfolio ranking', HeadingLevel.HEADING_2),
    ...rankingTable(scorecards),
    heading('Individual scorecards', HeadingLevel.HEADING_2),
  ];

  if (!scorecards.length) {
    children.push(mutedPara('No staff records.'));
  } else {
    for (const card of scorecards) {
      const detail = getDetails(card.staff?._id);
      children.push(...staffDetailChildren(card, detail?.assessments || []));
    }
  }

  children.push(...footerChildren());
  return packDocument('GAT Staff Performance Scorecards', children);
};

/**
 * Single-staff scorecard report.
 */
const buildIndividualReportDocx = async ({
  staff,
  card,
  assessments = [],
  generatedBy,
  filters,
} = {}) => {
  const staffCard = card || {
    staff,
    assessmentCount: assessments.filter((a) => a.status === 'completed').length,
    averagePercent: null,
    latestAssessmentDate: null,
    band: null,
  };

  const title = `Scorecard — ${staff?.name || 'Staff'}`;
  const children = [
    heading(title),
    ...metaChildren(generatedBy, filters),
    ...staffDetailChildren(staffCard, assessments),
    ...footerChildren(),
  ];

  return packDocument(title, children);
};

module.exports = {
  formatIsoDate,
  safeFilenamePart,
  buildPortfolioReportDocx,
  buildIndividualReportDocx,
};
